language: python

python:
  - '3.2'
env:
  - GI_INSTALL="python3-gi"
  - GI_INSTALL="python-gi"

matrix:
  exclude:
    - env: GI_INSTALL="python3-gi"
      python: "2.7"
    - env: GI_INSTALL="python-gi"
      python: "3.2"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-gi gir1.2-gtk-3.0 gtk+3.0
  - sudo apt-get install libwebkitgtk-3.0-0 python-webkit
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

virtualenv:
  system_site_packages: true
  
script:
  - python MainWindow.py
