language: python

python:
  - '3.4'

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-gi gir1.2-gtk-3.0

pyvenv:
  system_site_packages: True

script:
  - python MainWindow.py
