language: python

python:
  - '3.4'

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-gi gir1.2-gtk-3.0
  - deactivate
  - source ~/virtualenv/python3.4/bin/activate
  
install:
  - pip install pygobject

script:
  - python MainWindow.py
